### ISSUE TITLE
Does starcoin think public (script) needs to be replaced with public entry

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-ide#38]
Does starcoin think public (script) needs to be replaced with public (script)

![image](https://user-images.githubusercontent.com/1449069/181044046-3c427ad8-791e-45b6-b278-90467ba932bf.png)

**Comment by jolestar** [comment]
Starcoin support `public entry` in the branch https://github.com/starcoinorg/starcoin/pull/3424

**Comment by yubing744** [comment]
Ok, I'll try if I can add a switch to disable this warning?

**Comment by jolestar** [comment]
> Ok, I'll try if I can add a switch to disable this warning?

I think we can disable the warning first, after starcoin with new move version release, then we can enable it.

**Comment by jolestar** [comment]
> Ok, I'll try if I can add a switch to disable this warning?

I think we can disable the warning first, after starcoin with new move version release, then we can enable it.

**Comment by yubing744** [comment]
> > Ok, I'll try if I can add a switch to disable this warning?
> 
> I think we can disable the warning first, after starcoin with new move version release, then we can enable it.

starcoin-ide v0.7.9 already disabled this warning.
