### ISSUE TITLE
bug: The dependent MPM is not available

### ISSUE THREAD

**Issue by sophyallen** [starcoinorg/starcoin-ide#45]
# Bug Report

**Starcoin IDE version:**

tag: 0.7.3-alpha

**Current behavior:**

The following error occurred while running Build:
```
*  Executing task in folder simple-nft-mpm: /home/amin/web3/starcoin-ide/bin/mpm package build 

 /home/amin/web3/starcoin-ide/bin/mpm: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

 *  The terminal process "/usr/bin/bash '-c', '/home/amin/web3/starcoin-ide/bin/mpm package build'" failed to launch (exit code: 127). 
 *  Terminal will be reused by tasks, press any key to close it. 
```
**Expected behavior:**

**Steps to reproduce:**

- Wondows11 22H2
- WSL ubuntu 22.04
- VSCode V1.71.2 & starcoin-ide tag 0.7.3-alpha
- run build demo project, Move.toml

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by sophyallen** [comment]
MPM  relies on openssl version 1.1.x, but Ubuntu 22.04 defaults to 3.0.x

**Comment by jolestar** [comment]
https://github.com/starcoinorg/starcoin/issues/3784
