### ISSUE TITLE
[Feature Request] Release v0.6.0

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-ide#7]
Request release v0.6.0

Features:
1. Support mpm (move package manager)
2. Support github action to run test

**Comment by yubing744** [comment]
@jolestar I tested v1.11.7-rc, and the Windows line break problem is still not resolved.

![image](https://user-images.githubusercontent.com/1449069/166126473-b16c680f-d78b-41ba-8354-b5787168697f.png)

![image](https://user-images.githubusercontent.com/1449069/166126485-318e6291-9521-48a8-853d-afdc058027e0.png)

Failed github test workflow:
https://github.com/starcoinorg/starcoin-ide/runs/6243158834?check_suite_focus=true

Related Issues:  
https://github.com/starcoinorg/starcoin/issues/3130
https://github.com/starcoinorg/starcoin/issues/3131

Related PR: 
https://github.com/starcoinorg/starcoin-ide/pull/6

**Comment by jolestar** [comment]
> @jolestar I tested v1.11.7-rc, and the Windows line break problem is still not resolved.
> 
> ![image](https://user-images.githubusercontent.com/1449069/166126473-b16c680f-d78b-41ba-8354-b5787168697f.png)
> 
> ![image](https://user-images.githubusercontent.com/1449069/166126485-318e6291-9521-48a8-853d-afdc058027e0.png)
> 
> Failed github test workflow: https://github.com/starcoinorg/starcoin-ide/runs/6243158834?check_suite_focus=true
> 
> Related Issues: [starcoinorg/starcoin#3130](https://github.com/starcoinorg/starcoin/issues/3130) [starcoinorg/starcoin#3131](https://github.com/starcoinorg/starcoin/issues/3131)
> 
> Related PR: #6

Can you try to remove the `$HOME/.move` and set the git option?

**Comment by jolestar** [comment]
The CI also need to set the git option.

**Comment by yubing744** [comment]
> The CI also neet to set the git option.

@jolestar Is it possible to execute dos2unix after cloning?  
This eliminates the need for developers to configure git options

**Comment by jolestar** [comment]
> > The CI also needs to set the git option.
> 
> @jolestar Is it possible to execute dos2unix after cloning? This eliminates the need for developers to configure git options

The source code at `$HOME/.move` is managed by the mpm dependency manager, I think the better solution should be the compiler handling this  https://github.com/move-language/move/pull/18.

Let users configure git options is a workaround solution.

**Comment by yubing744** [comment]
@jolestar On windows platform, newline is CRLF(\r\n), but [this PR](https://github.com/move-language/move/pull/18) says to add CR(\r) as newline.

![image](https://user-images.githubusercontent.com/1449069/166135803-7b4d59ea-5ead-4fa1-98ea-e89d4fbb5d81.png)

**Comment by jolestar** [comment]
> @jolestar On windows platform, newline is CRLF(\r\n), but [this PR](https://github.com/move-language/move/pull/18) says to add CR(\r) as newline.
> 

I think the `\n` is already supported, so we just need to support `\r`. @LemonHX

**Comment by yubing744** [comment]
@jolestar I made a PR(https://github.com/move-language/move/pull/90) to solve the line break problem on the Windows platform.

**Comment by yubing744** [comment]
@jolestar All three platforms passed the test cases, I will release v0.6.0-alpha

**Comment by yubing744** [comment]
@jolestar I released v0.6.0-alpha and manually tested windows platform and mac platform.

**Comment by jolestar** [comment]
starcoin release https://github.com/starcoinorg/starcoin/releases/tag/v1.11.9

**Comment by yubing744** [comment]
> starcoin release https://github.com/starcoinorg/starcoin/releases/tag/v1.11.9

I updated to the latest version

**Comment by yubing744** [comment]
@jolestar I have released [v0.6.1](https://github.com/starcoinorg/starcoin-ide/releases/tag/v0.6.1), using the latest mpm v1.11.9.
